from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from datetime import date
from pathlib import Path
from typing import Any

SOURCE = (
    "https://raw.githubusercontent.com/BerriAI/litellm/main/"
    "model_prices_and_context_window.json"
)
SOURCE_LICENSE = "MIT"
TARGET = Path(__file__).resolve().parent.parent / "promptkit" / "data" / "pricing.json"

PROVIDERS = {
    "openai": "openai",
    "anthropic": "anthropic",
    "groq": "groq",
    "deepseek": "deepseek",
    "mistral": "mistral",
    "together_ai": "together",
    "xai": "xai",
}

SKIP_MARKERS = (
    "audio",
    "realtime",
    "transcribe",
    "tts",
    "embedding",
    "moderation",
    "image",
    "rerank",
)

SKIP_PREFIXES = ("together-ai-", "ft:", "sample_spec")

CURATED = {
    "claude-3-5-sonnet": (3.0, 15.0, "anthropic"),
    "claude-3-5-haiku": (0.8, 4.0, "anthropic"),
}


def fetch(url: str) -> dict[str, Any]:
    with urllib.request.urlopen(url, timeout=60) as response:
        payload: dict[str, Any] = json.load(response)

    return payload


def per_million(value: float | None) -> float | None:
    if value is None:
        return None

    return round(value * 1_000_000, 6)


def bare_name(name: str) -> str:
    return name.rsplit("/", 1)[-1]


def is_wanted(name: str, entry: Any) -> bool:
    if not isinstance(entry, dict) or name == "sample_spec":
        return False

    if entry.get("mode") != "chat":
        return False

    if entry.get("litellm_provider") not in PROVIDERS:
        return False

    if name.startswith(SKIP_PREFIXES):
        return False

    if any(marker in bare_name(name) for marker in SKIP_MARKERS):
        return False

    return entry.get("input_cost_per_token") is not None


def build(source: dict[str, Any]) -> tuple[dict[str, Any], list[str]]:
    candidates: dict[str, set[tuple[float, float]]] = {}
    chosen: dict[str, dict[str, Any]] = {}

    for name, entry in source.items():
        if not is_wanted(name, entry):
            continue

        input_rate = per_million(entry.get("input_cost_per_token"))
        output_rate = per_million(entry.get("output_cost_per_token"))

        if input_rate is None or output_rate is None:
            continue

        key = bare_name(name)
        candidates.setdefault(key, set()).add((input_rate, output_rate))
        chosen[key] = {
            "input": input_rate,
            "output": output_rate,
            "provider": PROVIDERS[entry["litellm_provider"]],
        }

    ambiguous = sorted(k for k, rates in candidates.items() if len(rates) > 1)

    models = {
        name: entry
        for name, entry in chosen.items()
        if len(candidates.get(name, ())) == 1
    }

    for name, (input_rate, output_rate, provider) in CURATED.items():
        models.setdefault(
            name, {"input": input_rate, "output": output_rate, "provider": provider}
        )

    models["ollama"] = {"input": 0.0, "output": 0.0, "provider": "ollama"}

    return (
        {
            "_meta": {
                "updated": date.today().isoformat(),
                "source": SOURCE,
                "source_license": SOURCE_LICENSE,
                "note": "Generated by scripts/refresh_pricing.py. Do not edit by hand.",
                "units": "USD per 1,000,000 tokens",
                "curated": sorted(CURATED),
            },
            "models": dict(sorted(models.items())),
        },
        ambiguous,
    )


def render(data: dict[str, Any]) -> str:
    return json.dumps(data, indent=2, sort_keys=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Refresh the vendored model pricing snapshot."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the snapshot is out of date, without writing",
    )
    args = parser.parse_args(argv)

    try:
        source = fetch(SOURCE)
    except OSError as e:
        print(f"error: could not fetch {SOURCE}: {e}", file=sys.stderr)

        return 2

    fresh, ambiguous = build(source)
    rendered = render(fresh)
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""

    def rates(text: str) -> dict[str, Any]:
        if not text:
            return {}

        loaded: dict[str, Any] = json.loads(text).get("models", {})

        return loaded

    old, new = rates(current), fresh["models"]

    added = sorted(set(new) - set(old))
    removed = sorted(set(old) - set(new))
    changed = sorted(k for k in set(old) & set(new) if old[k] != new[k])

    if ambiguous:
        print(
            f"skipped {len(ambiguous)} ambiguous name(s) priced differently by "
            f"two providers: {', '.join(ambiguous[:6])}"
        )

    if not (added or removed or changed):
        print(f"pricing is up to date ({len(new)} models)")

        return 0

    print(f"{len(added)} added, {len(removed)} removed, {len(changed)} changed")

    for name in changed:
        print(
            f"  ~ {name}: {old[name]['input']}/{old[name]['output']}"
            f" -> {new[name]['input']}/{new[name]['output']}"
        )

    for name in added[:20]:
        print(f"  + {name}: {new[name]['input']}/{new[name]['output']}")

    if len(added) > 20:
        print(f"  + ... and {len(added) - 20} more")

    for name in removed[:20]:
        print(f"  - {name}")

    if args.check:
        print("\nrun `make pricing-refresh` to update the snapshot", file=sys.stderr)

        return 1

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"\nwrote {TARGET.relative_to(Path.cwd())}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
